name: TransformLanguage
version: 'R0.1-0.0.1-BETA<SNAPSHOT>'
author: 'Xiao_QDev, hekuo5310'
description: 'This is a very good plugin'
load: STARTUP
main: org.transformLanguage.TransformLanguage
api-version: '1.21'

commands:
    transformLanguage:
        description: 'TransformLanguage'
        usage: '/transformLanguage <command> [args]'
        aliases: [tfl]
        permission: transformLanguage.admin
permissions:
  transformLanguage.admin:
      description: 'Allows access to admin commands'
      default: op
